/**
 * Minimal TopoJSON ? GeoJSON converter for polygons/multi-polygons.
 * Supports the structures generated by Power BI custom maps.
 */
export function topologyToFeatureCollection(topology, targetKeys) {
  if (!topology || typeof topology !== "object") {
    return { type: "FeatureCollection", features: [] };
  }

  const { arcs = [], transform } = topology;
  const scale = transform?.scale ?? [1, 1];
  const translate = transform?.translate ?? [0, 0];

  const absoluteArcs = arcs.map((arc) => {
    let x = 0;
    let y = 0;
    return arc.map(([dx, dy]) => {
      x += dx;
      y += dy;
      return [x * scale[0] + translate[0], y * scale[1] + translate[1]];
    });
  });

  const arcCache = new Map();
  const getArc = (index) => {
    if (arcCache.has(index)) {
      return arcCache.get(index);
    }

    const isReversed = index < 0;
    const absIndex = isReversed ? ~index : index;
    const base = absoluteArcs[absIndex] ?? [];
    const points = isReversed ? [...base].reverse() : base;
    arcCache.set(index, points);
    return points;
  };

  const joinArcs = (indices) => {
    const coordinates = [];
    indices.forEach((arcIndex, idx) => {
      const points = getArc(arcIndex);
      if (!points.length) {
        return;
      }
      const toAdd = idx === 0 ? points : points.slice(1);
      coordinates.push(...toAdd);
    });
    if (coordinates.length) {
      const [x0, y0] = coordinates[0];
      const [x1, y1] = coordinates[coordinates.length - 1];
      if (x0 !== x1 || y0 !== y1) {
        coordinates.push([x0, y0]);
      }
    }
    return coordinates;
  };

  const convertGeometry = (geometry) => {
    if (!geometry) {
      return null;
    }

    switch (geometry.type) {
      case "Polygon":
        return {
          type: "Polygon",
          coordinates: geometry.arcs.map((ring) => joinArcs(ring)),
        };
      case "MultiPolygon":
        return {
          type: "MultiPolygon",
          coordinates: geometry.arcs.map((poly) => poly.map((ring) => joinArcs(ring))),
        };
      case "GeometryCollection":
        return {
          type: "GeometryCollection",
          geometries: geometry.geometries
            ?.map((child) => convertGeometry(child))
            .filter(Boolean),
        };
      default:
        return null;
    }
  };

  const toFeatures = (object) => {
    if (!object) {
      return [];
    }

    if (object.type === "GeometryCollection") {
      return object.geometries?.flatMap((geom) => toFeatures(geom)) ?? [];
    }

    const geometry = convertGeometry(object);
    if (!geometry) {
      return [];
    }

    const feature = {
      type: "Feature",
      properties: { ...(object.properties ?? {}) },
      geometry,
    };

    return [feature];
  };

  const objects = topology.objects ?? {};
  const topKeys = targetKeys?.length ? targetKeys : Object.keys(objects);

  const features = topKeys.flatMap((key) => toFeatures(objects[key]));

  return { type: "FeatureCollection", features };
}
